### ISSUE TITLE
Windows compiled binaries

### ISSUE THREAD

**Issue by lufol** [ETH3D/badslam#38]
I'd like to point out that you really have a great project! 
Unfortunaltely I am unable to find the Windows binaries.
From the Readme:
> For Windows, an executable compiled with Visual Studio 2019 is provided

Could you please provide the link for the binary?

Best

**Comment by puzzlepaint** [comment]
See the zip files provided as [releases](https://github.com/ETH3D/badslam/releases). At the moment, the most recent one is version [1.0.1](https://github.com/ETH3D/badslam/releases/download/v1.0.1/badslam-1.0.1.zip).

**Comment by lufol** [comment]
Thank you! Maybe a link to the relases on the readme would be useful? I could create a PR for that if this is desired.

**Comment by puzzlepaint** [comment]
Thanks for the suggestion, I added the link.
