### ISSUE TITLE
FATL| Cuda Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Young532042725** [ETH3D/badslam#42]
hi friends,  i am using this SLAM,  
"make -j badslam"
"make -j badslam_test" are all ok.
But, when i run the "./build_RelWithDebInfo/applications/badslam/badslam_test", some errors occur!
I use an Nvidia GeForce GT730 graphic card. CUDA 10.0. Would you please give me some advice? Thanks!!
![Screenshot from 2020-02-20 11-15-26](https://user-images.githubusercontent.com/34529308/74899190-24481800-53d7-11ea-8eb0-c02eea3e1095.png)

**Comment by puzzlepaint** [comment]
The different variants of the GT 730 card all have at most compute capability 3.5. As stated in the Readme, as-is the application requires compute capability 5.3. So this failure is expected. As for possible ways around this, see #23.
