### ISSUE TITLE
"CUDA error: invalid device function" while auto_tunning

### ISSUE THREAD

**Issue by AreteQin** [ETH3D/badslam#47]
Hi guys,

I am trying to run BAD_SLAM on my laptop with GTX 850M (Compute Capability 5.0) in Ubuntu 1804.

I have passed "make -j badslam" and "make -j badslam_test".

However, I met an error while running Auto_tunning as shown below
![image](https://user-images.githubusercontent.com/38554510/77097503-ce33b800-6a08-11ea-9ae8-7417e45f2a25.png)

I tried to solve this with this method, but it was not working: https://github.com/ETH3D/badslam/issues/34

Please help me with this and I can provide more logs if needed. Thanks in advance!

**Comment by puzzlepaint** [comment]
Such a failure is expected, since the application requires at least CUDA compute capability 5.3, as stated in the ReadMe. This topic is already covered by issue #23, thus I will close this issue. See #23 for a suggestion on how to modify the application to make it work.
