### ISSUE TITLE
Running in debug mode, reporting "too many resources requested".

### ISSUE THREAD

**Issue by gongyeted** [ETH3D/badslam#56]
I have successfully run the program in RelWithDebInfo mode with using auto_tune_parameters.py to fix "too many resources requested" problem. Then I building it successfully in debug mode, but running with the "too many resources requested" again in debug mode. Would you please give me some advice?

**Comment by puzzlepaint** [comment]
Did you try running the auto-tuning script again for the executable built in Debug mode? I think that it might be possible that the different flags for compiling in debug mode could lead to different resource requirements for the CUDA kernels, such that it might be needed to choose different block sizes.
