### ISSUE TITLE
Structure SDK

### ISSUE THREAD

**Issue by BinuxLiu** [ETH3D/badslam#68]
Hello, what is the version of structure SDK you are using? 
The latest firmware update to 1.0 and SDK update to 0.9, badslam can't run, so I'm going to downgrade.
I guess the SDK is 0.7?

**Comment by puzzlepaint** [comment]
Yes, I think that I ran it with SDK versions 0.7.x.

**Comment by BinuxLiu** [comment]
Thank you！
