### ISSUE TITLE
opengv 3rdparty

### ISSUE THREAD

**Issue by zellx3** [ETH3D/badslam#91]
As it mentioned in README opengv only could get compiled in debug mode, I had been noticed it's only used for loop_detector, for ransac model fitting, do you think is there any possibility to use opencv or a lightweight library instead of opengv?

**Comment by puzzlepaint** [comment]
While I don't know which alternative libraries could be suitable, another workaround might be to remove unneeded parts from the OpenGV build in case the issue arises from a part that isn't needed.

**Comment by zellx3** [comment]
Actually issue rise because I insist to have the 3rdparty build in package manager and not using third-party folder integrated in the repo, that's why I need to use opengv from it's github repo. As I understood that even with the third-party in the repo issue with the build in release exist ( I should mention that I was successful to build opengv but release take very long time and memory usage to get finished).  So my alternative was managing to remove it from dependencies.

Seems that, what we really need here is to calculating transformation between old points and current points. I guess it's not even necessory to have ransac maybe [Eigen::umeyama()](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#title25) should be enough
